# Generated by Django 4.2.1 on 2023-06-13 02:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FName', models.CharField(max_length=50, verbose_name='First Name')),
                ('LName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('grade', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long.'), django.core.validators.RegexValidator(message='Password must contain at least one letter and one number.', regex='^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]+$')], verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Maths_Score',
            fields=[
                ('point', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Points')),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='maths_score', serialize=False, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Words_Score',
            fields=[
                ('point', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Points')),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='words_score', serialize=False, to='api.user')),
            ],
        ),
    ]
