# Generated by Django 4.2.1 on 2023-06-13 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=125, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long.'), django.core.validators.RegexValidator(message='Password must contain at least one letter and one number.', regex='^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]+$')], verbose_name='Password'),
        ),
    ]
