# Generated by Django 4.2.1 on 2023-06-13 20:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScribbleQuest_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('FName', models.CharField(max_length=50, verbose_name='First Name')),
                ('LName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('grade', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('password', models.CharField(max_length=125, validators=[django.core.validators.MinLengthValidator(8, message='Password must be at least 8 characters long.'), django.core.validators.RegexValidator(message='Password must contain at least one letter and one number.', regex='^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]+$')], verbose_name='Password')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='maths_score',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='maths_score', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='words_score',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='words_score', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
