# Generated by Django 4.2.1 on 2023-06-13 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_scribblequest_user_alter_maths_score_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maths_score',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='maths_score', serialize=False, to='api.scribblequest_user'),
        ),
        migrations.AlterField(
            model_name='words_score',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='words_score', serialize=False, to='api.scribblequest_user'),
        ),
    ]
